BASE=c:/prop-sx
CC1B=$(BASE)/cc1b/free
C4SX=$(BASE)/c4sx

CC=$(CC1B)/cc1b.exe
CFLAGS=-I$(CC1B) -I$(C4SX) -I$(BASE)/lib -dc
CC1B2SX=$(C4SX)/cc1b2sx.exe

%.src: %.foo
	$(CC1B2SX) < $< > $@

%.hex %.foo: %.c
	$(CC) $(CFLAGS) -a$(<:.c=.foo) $<
