#ifndef __RANDOM_C__
#define __RANDOM_C__

/* this code is ripped off from the code generated by the SX/B compiler */

uns16 random_seed;

uns16
random(void)
{
    uns16 tmp;
    unsigned char rs_MSB @ random_seed.high8;
    unsigned char rs_LSB @ random_seed;

    if (random_seed == 0) rs_MSB = rs_MSB ^ 255;
    W = 0x80;
    if ((rs_MSB & (1<<6)) != 0) rs_MSB = rs_MSB ^ W;
    if ((rs_MSB & (1<<4)) != 0) rs_MSB = rs_MSB ^ W;
    if ((rs_MSB & (1<<3)) != 0) rs_MSB = rs_MSB ^ W;
    W = rl(rs_MSB);
    rs_LSB = rl(rs_LSB);
    rs_MSB = rl(rs_MSB);

    return random_seed;
}

#endif
